const $=s=>document.querySelector(s);let selectedPod,restartTarget;
const api=async(path,options)=>{const r=await fetch(path,options),j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ns=()=>$('#namespace').value;
function age(then){let s=Math.max(0,Math.floor((Date.now()-Date.parse(then))/1000)),u=[[86400,'d'],[3600,'h'],[60,'m'],[1,'s']],out=[];for(const [n,l] of u){let q=Math.floor(s/n);if(q){out.push(q+l);s%=n}if(out.length===2)break}return out.join(' ')||'0s'}
function note(text,bad){$('#notice').textContent=text;$('#notice').className=bad?'error':'success'}
function ready(x){const s=x.status||{};return s.readyReplicas??s.numberReady??0} function desired(x){const s=x.status||{},p=x.spec||{};return s.replicas??s.currentNumberScheduled??p.replicas??0}
async function loadCluster(){const [nss,nodes]=await Promise.all([api('/api/namespaces'),api('/api/nodes')]),names=nss.items.map(x=>x.metadata.name);$('#namespace').innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join('');$('#namespace').value=names.find(x=>x==='default')||names[0];$('#namespaceList').innerHTML=names.map(n=>`<button class="ns" data-ns="${esc(n)}">${esc(n)}</button>`).join('');$('#nodes').innerHTML=nodes.items.map(n=>{const c=(n.status.conditions||[]).find(x=>x.type==='Ready');return `<div class="node-card" data-node="${esc(n.metadata.name)}"><b class="${c?.status==='True'?'ok':'bad'}">●</b> <strong>${esc(n.metadata.name)}</strong><span class="metric">Loading utilization…</span></div>`}).join('');document.querySelectorAll('.ns').forEach(b=>b.onclick=()=>{$('#namespace').value=b.dataset.ns;loadNamespace()});loadNodeMetrics()}
async function loadNodeMetrics(){try{const d=await api('/api/node-metrics'),byName=Object.fromEntries(d.items.map(x=>[x.name,x]));document.querySelectorAll('[data-node]').forEach(el=>{const m=byName[el.dataset.node];el.querySelector('.metric').innerHTML=m?`CPU <b>${m.cpu}</b> <em>${m.cpuPercent}</em><br>MEM <b>${m.memory}</b> <em>${m.memoryPercent}</em>`:'No metrics'})}catch(e){document.querySelectorAll('[data-node] .metric').forEach(x=>x.textContent='Metrics Server unavailable')}}
function workloadRow(w){const k=w.kind.toLowerCase(),canScale=k==='deployment'||k==='statefulset';return `<tr><td>${esc(w.kind)}</td><td><b>${esc(w.metadata.name)}</b></td><td>${ready(w)} / ${desired(w)}</td><td><button class="context-workload" data-kind="${k}" data-name="${esc(w.metadata.name)}">Context</button> ${canScale?`<button class="scale-workload" data-kind="${k}" data-name="${esc(w.metadata.name)}" data-replicas="${desired(w)}">Scale</button> `:''}<button class="restart-workload" data-kind="${k}" data-name="${esc(w.metadata.name)}">Restart</button></td></tr>`}
async function loadNamespace(){try{note('Loading '+ns()+'…');const [w,p,e]=await Promise.all([api('/api/workloads?namespace='+encodeURIComponent(ns())),api('/api/pods?namespace='+encodeURIComponent(ns())),api('/api/events?namespace='+encodeURIComponent(ns()))]);$('#workloads').innerHTML=`<h2>Workloads <small>${esc(ns())}</small></h2><p class="muted">Context maps a workload to its Pods, Services, HPA, endpoints, and Ingress routes.</p><table><thead><tr><th>Kind</th><th>Name</th><th>Ready</th><th></th></tr></thead><tbody>${w.items.map(workloadRow).join('')||'<tr><td colspan="4">No workloads found</td></tr>'}</tbody></table>`;$('#pods').innerHTML=`<h2>Pods <small id="podMetricState">live utilization</small></h2><table><thead><tr><th>Name</th><th>Phase</th><th>Age</th><th>CPU</th><th>Memory</th><th>Restarts</th><th></th></tr></thead><tbody>${p.items.map(x=>{const restarts=(x.status.containerStatuses||[]).reduce((n,c)=>n+c.restartCount,0);return `<tr data-pod-row="${esc(x.metadata.name)}"><td><b>${esc(x.metadata.name)}</b></td><td>${esc(x.status.phase)}</td><td title="${esc(x.metadata.creationTimestamp)}">${age(x.metadata.creationTimestamp)}</td><td class="cpu">Loading…</td><td class="memory">Loading…</td><td>${restarts}</td><td><button class="logs" data-pod="${esc(x.metadata.name)}">Logs</button> <button class="restart-pod" data-pod="${esc(x.metadata.name)}">Restart</button></td></tr>`}).join('')||'<tr><td colspan="7">No pods found</td></tr>'}</tbody></table>`;$('#events').innerHTML=`<h2>Events</h2><table><thead><tr><th>When</th><th>Type</th><th>Reason</th><th>Message</th></tr></thead><tbody>${e.items.slice(-100).reverse().map(x=>`<tr><td>${esc(x.lastTimestamp||x.eventTime||x.metadata.creationTimestamp)}</td><td>${esc(x.type)}</td><td>${esc(x.reason)}</td><td>${esc(x.message)}</td></tr>`).join('')||'<tr><td colspan="4">No events found</td></tr>'}</tbody></table>`;document.querySelectorAll('.logs').forEach(b=>b.onclick=()=>openLogs(b.dataset.pod));document.querySelectorAll('.context-workload').forEach(b=>b.onclick=()=>openContext(b.dataset.kind,b.dataset.name));document.querySelectorAll('.scale-workload').forEach(b=>b.onclick=()=>openScale(b.dataset.kind,b.dataset.name,b.dataset.replicas));document.querySelectorAll('.restart-workload').forEach(b=>b.onclick=()=>openRestart(b.dataset.kind,b.dataset.name,false));document.querySelectorAll('.restart-pod').forEach(b=>b.onclick=()=>openRestart('pod',b.dataset.pod,true));loadPodMetrics();note('Showing '+ns())}catch(e){note(e.message,true)}}
async function loadPodMetrics(){try{const d=await api('/api/pod-metrics?namespace='+encodeURIComponent(ns())),byName=Object.fromEntries(d.items.map(x=>[x.name,x]));document.querySelectorAll('tr[data-pod-row]').forEach(row=>{const m=byName[row.dataset.podRow];row.querySelector('.cpu').textContent=m?m.cpu:'—';row.querySelector('.memory').textContent=m?m.memory:'—'})}catch(e){document.querySelectorAll('tr[data-pod-row] .cpu, tr[data-pod-row] .memory').forEach(x=>x.textContent='unavailable');$('#podMetricState').textContent='utilization unavailable: '+e.message}}
async function openLogs(p){selectedPod=p;$('#logTitle').textContent='Logs · '+p;$('#logs').textContent='Loading…';$('#logsDialog').showModal();loadLogs()}
async function loadLogs(){try{const q=new URLSearchParams({namespace:ns(),pod:selectedPod,previous:$('#previous').checked});$('#logs').textContent=(await api('/api/logs?'+q)).logs||'(no logs)'}catch(e){$('#logs').textContent=e.message}}
function openRestart(kind,name,isPod){restartTarget={kind,name,isPod};$('#restartText').textContent=isPod?`You are about to delete pod/${name}; its controller should recreate it in namespace ${ns()}.`:`You are about to restart ${kind}/${name} in namespace ${ns()}.`;$('#confirmation').value='';$('#confirmation').placeholder='RESTART';$('#restartDialog').showModal()}
function contextTable(headers,rows,empty){return `<table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}">${empty||'None found'}</td></tr>`}</tbody></table>`}
async function openContext(kind,name){
  const dialog=$('#podDialog'),box=$('#podDetail');
  box.textContent='Loading workload application context…';dialog.showModal();
  try{
    const d=await api('/api/workload-context?namespace='+encodeURIComponent(ns())+'&kind='+encodeURIComponent(kind)+'&name='+encodeURIComponent(name));
    const pods=d.pods||[],services=d.services||[],hpas=d.hpas||[];
    const podRows=pods.map(function(p){
      const status=p.status||{},spec=p.spec||{},containers=status.containerStatuses||[];
      return '<tr><td><b>'+esc(p.metadata.name)+'</b></td><td>'+esc(status.phase||'Unknown')+'</td><td>'+containers.filter(function(c){return c.ready}).length+'/'+(spec.containers||[]).length+'</td></tr>';
    }).join('');
    const hpaRows=hpas.map(function(h){
      const spec=h.spec||{},status=h.status||{};
      return '<tr><td><b>'+esc(h.metadata.name)+'</b></td><td>'+esc(status.currentReplicas==null?'—':status.currentReplicas)+'</td><td>'+esc(spec.minReplicas==null?1:spec.minReplicas)+'–'+esc(spec.maxReplicas==null?'—':spec.maxReplicas)+'</td></tr>';
    }).join('');
    const serviceRows=services.map(function(s){
      const routes=(s.routes||[]).map(function(r){return String(r.host||'*')+String(r.path||'/')}).join(', ')||'—';
      const ports=(s.ports||[]).map(function(p){
        const target=p.targetPort==null?p.port:p.targetPort;
        const nodePort=p.nodePort==null?'':' · nodePort '+p.nodePort;
        return (p.protocol||'TCP')+' '+p.port+' → '+target+nodePort;
      }).join('<br>')||'—';
      return '<tr><td><b>'+esc(s.name)+'</b></td><td>'+esc(s.type)+'</td><td>'+ports+'</td><td>'+esc(s.readyEndpoints)+'/'+esc(s.endpointCount)+'</td><td>'+esc(routes)+'</td></tr>';
    }).join('');
    box.innerHTML='<h2>Application context · '+esc(kind)+'/'+esc(name)+'</h2>'+
      '<p class="muted">Live relationships resolved from workload selectors, Services, EndpointSlices, HPA targets, and Ingress backends.</p>'+
      '<h3>Pods · '+pods.length+'</h3>'+contextTable(['Name','Phase','Ready'],podRows,'No Pods match this workload selector.')+
      '<h3>Autoscaling</h3>'+contextTable(['HPA','Current','Range'],hpaRows,'No HPA targets this workload.')+
      '<h3>Services, endpoints & routes</h3>'+contextTable(['Service','Type','Ports','Ready endpoints','Ingress routes'],serviceRows,'No Service selector matches this workload.');
  }catch(e){box.textContent=e.message}
}
function openScale(kind,name,current){$('#scaleText').textContent=`You are about to scale ${kind}/${name} in namespace ${ns()}. Current desired replicas: ${current}.`;$('#replicaCount').value=current;$('#scaleConfirmation').value='';$('#scaleDialog').showModal()}
$('#confirmScale').onclick=async e=>{e.preventDefault();try{const text=$('#scaleText').textContent.match(/scale ([^/]+)\/([^ ]+)/);if(!text)throw Error('Invalid scale target');const r=await api('/api/scale',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({namespace:ns(),kind:text[1],name:text[2],replicas:$('#replicaCount').value,confirmation:$('#scaleConfirmation').value})});$('#scaleDialog').close();note(r.message);setTimeout(loadNamespace,1000)}catch(x){note(x.message,true)}};
$('#confirmRestart').onclick=async e=>{e.preventDefault();try{const r=await api(restartTarget.isPod?'/api/restart-pod':'/api/restart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...restartTarget,namespace:ns(),confirmation:$('#confirmation').value})});$('#restartDialog').close();note(r.message);loadNamespace()}catch(e){note(e.message,true)}};
$('#namespace').onchange=loadNamespace;$('#refresh').onclick=()=>loadCluster().then(loadNamespace);$('#reloadLogs').onclick=e=>{e.preventDefault();loadLogs()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$('#'+b.dataset.tab).classList.remove('hidden')});loadCluster().then(loadNamespace).catch(e=>note(e.message,true));
