const $=s=>document.querySelector(s);let selectedPod,restartTarget;
const api=async(path,options)=>{const r=await fetch(path,options),j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ns=()=>$('#namespace').value;
function age(then){let s=Math.max(0,Math.floor((Date.now()-Date.parse(then))/1000)),u=[[86400,'d'],[3600,'h'],[60,'m'],[1,'s']],out=[];for(const [n,l] of u){let q=Math.floor(s/n);if(q){out.push(q+l);s%=n}if(out.length===2)break}return out.join(' ')||'0s'}
function note(text,bad){$('#notice').textContent=text;$('#notice').className=bad?'error':'success'}
function ready(x){const s=x.status||{};return s.readyReplicas??s.numberReady??0} function desired(x){const s=x.status||{},p=x.spec||{};return s.replicas??s.currentNumberScheduled??p.replicas??0}
async function loadCluster(){const [nss,nodes]=await Promise.all([api('/api/namespaces'),api('/api/nodes')]),names=nss.items.map(x=>x.metadata.name);$('#namespace').innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join('');$('#namespace').value=names.find(x=>x==='default')||names[0];$('#namespaceList').innerHTML=names.map(n=>`<button class="ns" data-ns="${esc(n)}">${esc(n)}</button>`).join('');$('#nodes').innerHTML=nodes.items.map(n=>{const c=(n.status.conditions||[]).find(x=>x.type==='Ready');return `<div class="node-card" data-node="${esc(n.metadata.name)}"><b class="${c?.status==='True'?'ok':'bad'}">●</b> <strong>${esc(n.metadata.name)}</strong><span class="metric">Loading utilization…</span></div>`}).join('');document.querySelectorAll('.ns').forEach(b=>b.onclick=()=>{$('#namespace').value=b.dataset.ns;loadNamespace()});loadNodeMetrics()}
async function loadNodeMetrics(){try{const d=await api('/api/node-metrics'),byName=Object.fromEntries(d.items.map(x=>[x.name,x]));document.querySelectorAll('[data-node]').forEach(el=>{const m=byName[el.dataset.node];el.querySelector('.metric').innerHTML=m?`CPU <b>${m.cpu}</b> <em>${m.cpuPercent}</em><br>MEM <b>${m.memory}</b> <em>${m.memoryPercent}</em>`:'No metrics'})}catch(e){document.querySelectorAll('[data-node] .metric').forEach(x=>x.textContent='Metrics Server unavailable')}}
function workloadRow(w){const k=w.kind.toLowerCase();return `<tr><td>${esc(w.kind)}</td><td><b>${esc(w.metadata.name)}</b></td><td>${ready(w)} / ${desired(w)}</td><td><button class="restart-workload" data-kind="${k}" data-name="${esc(w.metadata.name)}">Restart</button></td></tr>`}
async function loadNamespace(){try{note('Loading '+ns()+'…');const [w,p,e]=await Promise.all([api('/api/workloads?namespace='+encodeURIComponent(ns())),api('/api/pods?namespace='+encodeURIComponent(ns())),api('/api/events?namespace='+encodeURIComponent(ns()))]);$('#workloads').innerHTML=`<h2>Workloads <small>${esc(ns())}</small></h2><table><thead><tr><th>Kind</th><th>Name</th><th>Ready</th><th></th></tr></thead><tbody>${w.items.map(workloadRow).join('')||'<tr><td colspan="4">No workloads found</td></tr>'}</tbody></table>`;$('#pods').innerHTML=`<h2>Pods <small id="podMetricState">live utilization</small></h2><table><thead><tr><th>Name</th><th>Phase</th><th>Age</th><th>CPU</th><th>Memory</th><th>Restarts</th><th></th></tr></thead><tbody>${p.items.map(x=>{const restarts=(x.status.containerStatuses||[]).reduce((n,c)=>n+c.restartCount,0);return `<tr data-pod-row="${esc(x.metadata.name)}"><td><b>${esc(x.metadata.name)}</b></td><td>${esc(x.status.phase)}</td><td title="${esc(x.metadata.creationTimestamp)}">${age(x.metadata.creationTimestamp)}</td><td class="cpu">Loading…</td><td class="memory">Loading…</td><td>${restarts}</td><td><button class="logs" data-pod="${esc(x.metadata.name)}">Logs</button> <button class="restart-pod" data-pod="${esc(x.metadata.name)}">Restart</button></td></tr>`}).join('')||'<tr><td colspan="7">No pods found</td></tr>'}</tbody></table>`;$('#events').innerHTML=`<h2>Events</h2><table><thead><tr><th>When</th><th>Type</th><th>Reason</th><th>Message</th></tr></thead><tbody>${e.items.slice(-100).reverse().map(x=>`<tr><td>${esc(x.lastTimestamp||x.eventTime||x.metadata.creationTimestamp)}</td><td>${esc(x.type)}</td><td>${esc(x.reason)}</td><td>${esc(x.message)}</td></tr>`).join('')||'<tr><td colspan="4">No events found</td></tr>'}</tbody></table>`;document.querySelectorAll('.logs').forEach(b=>b.onclick=()=>openLogs(b.dataset.pod));document.querySelectorAll('.restart-workload').forEach(b=>b.onclick=()=>openRestart(b.dataset.kind,b.dataset.name,false));document.querySelectorAll('.restart-pod').forEach(b=>b.onclick=()=>openRestart('pod',b.dataset.pod,true));loadPodMetrics();note('Showing '+ns())}catch(e){note(e.message,true)}}
async function loadPodMetrics(){try{const d=await api('/api/pod-metrics?namespace='+encodeURIComponent(ns())),byName=Object.fromEntries(d.items.map(x=>[x.name,x]));document.querySelectorAll('tr[data-pod-row]').forEach(row=>{const m=byName[row.dataset.podRow];row.querySelector('.cpu').textContent=m?m.cpu:'—';row.querySelector('.memory').textContent=m?m.memory:'—'})}catch(e){document.querySelectorAll('tr[data-pod-row] .cpu, tr[data-pod-row] .memory').forEach(x=>x.textContent='unavailable');$('#podMetricState').textContent='utilization unavailable: '+e.message}}
async function openLogs(p){selectedPod=p;$('#logTitle').textContent='Logs · '+p;$('#logs').textContent='Loading…';$('#logsDialog').showModal();loadLogs()}
async function loadLogs(){try{const q=new URLSearchParams({namespace:ns(),pod:selectedPod,previous:$('#previous').checked});$('#logs').textContent=(await api('/api/logs?'+q)).logs||'(no logs)'}catch(e){$('#logs').textContent=e.message}}
function openRestart(kind,name,isPod){restartTarget={kind,name,isPod};$('#restartText').textContent=isPod?`You are about to delete pod/${name}; its controller should recreate it in namespace ${ns()}.`:`You are about to restart ${kind}/${name} in namespace ${ns()}.`;$('#confirmation').value='';$('#confirmation').placeholder='RESTART';$('#restartDialog').showModal()}
$('#confirmRestart').onclick=async e=>{e.preventDefault();try{const r=await api(restartTarget.isPod?'/api/restart-pod':'/api/restart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...restartTarget,namespace:ns(),confirmation:$('#confirmation').value})});$('#restartDialog').close();note(r.message);loadNamespace()}catch(e){note(e.message,true)}};
$('#namespace').onchange=loadNamespace;$('#refresh').onclick=()=>loadCluster().then(loadNamespace);$('#reloadLogs').onclick=e=>{e.preventDefault();loadLogs()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$('#'+b.dataset.tab).classList.remove('hidden')});loadCluster().then(loadNamespace).catch(e=>note(e.message,true));
