(async()=>{
  const r=await fetch('/api/me');if(!r.ok){location.assign('/login.html');return}
  const me=await r.json(),identity=document.querySelector('#identity');identity.textContent=`${me.username} · ${me.role}`;
  const clock=document.createElement('span');clock.style.cssText='margin-right:12px;color:#9ec7f1;font-size:12px';identity.before(clock);
  try{const t=await fetch('/api/time').then(x=>x.json()),start=Date.now(),format=()=>clock.textContent=`Server time: ${new Date(t.epoch*1000+Date.now()-start).toLocaleString()} ${t.timezone}`;format();setInterval(format,1000)}catch(e){clock.textContent='Server time unavailable'}
  if(!['write','admin'].includes(me.role))document.head.insertAdjacentHTML('beforeend','<style>.restart-workload,.restart-pod,.scale-workload,.cronjob-action,.cronjob-edit,.hpa-edit{display:none!important}</style>');
  document.querySelector('#logout').onclick=async()=>{await fetch('/api/logout',{method:'POST'});location.assign('/login.html')};
  try{const c=await fetch('/api/config').then(x=>x.json());if(!c.scaleEnabled)document.head.insertAdjacentHTML('beforeend','<style>.scale-workload{display:none!important}</style>');if(!c.cronJobSuspendEnabled)document.head.insertAdjacentHTML('beforeend','<style>.cronjob-action{display:none!important}</style>');if(!c.cronJobEditEnabled)document.head.insertAdjacentHTML('beforeend','<style>.cronjob-edit{display:none!important}</style>');if(!c.hpaEditEnabled)document.head.insertAdjacentHTML('beforeend','<style>.hpa-edit{display:none!important}</style>');setInterval(()=>{if(!document.hidden)loadNamespace()},c.refreshSeconds*1000)}catch(e){}
  let allLogs='', logRequest=0, logNamespace='', savedRows=[];
  const dialog=document.querySelector('#logsDialog'),container=document.querySelector('#logContainer'),since=document.querySelector('#logSince'),search=document.querySelector('#logSearch'),output=document.querySelector('#logs');
  const controls=document.createElement('div');controls.className='tools';
  controls.innerHTML='<label>Source<select id="logSource"><option value="current">Current logs</option><option value="saved">Saved logs (PVC)</option></select></label><label id="savedPeriodField" hidden>Saved period<select id="savedLogDays"><option value="1">Last 24 hours</option><option value="7">Last 7 days</option><option value="30" selected>Last 30 days</option></select></label><label id="savedPodField" hidden>Pod name<select id="savedLogPod"><option value="">All saved Pods</option></select></label>';
  document.querySelector('#logTitle').after(controls);
  const source=$('#logSource'),days=$('#savedLogDays'),savedPod=$('#savedLogPod');
  function setSavedPod(p){savedPod.innerHTML='<option value="">All saved Pods</option>'+(p?'<option value="'+esc(p)+'">'+esc(p)+'</option>':'');savedPod.value=p||'';}
  const archiveStatus=document.createElement('p');archiveStatus.id='logArchiveStatus';archiveStatus.setAttribute('role','status');output.before(archiveStatus);
  function render(){const q=search.value.trim().toLowerCase();output.textContent=!q?allLogs:allLogs.split('\n').filter(x=>x.toLowerCase().includes(q)).join('\n')||'No matching log lines.'}
  function mode(){const saved=source.value==='saved';$('#savedPeriodField').hidden=!saved;$('#savedPodField').hidden=!saved;since.closest('label').hidden=saved;$('#previous').closest('label').hidden=saved;}
  function renderSaved(){const rows=savedRows.filter(x=>!container.value||x.container===container.value);allLogs=rows.length?rows.map(x=>'--- '+new Date(x.ts*1000).toLocaleString()+' · '+x.pod+' / '+x.container+(x.previous?' · previous container':'')+' ---\n'+x.text).join('\n\n'):'No saved log lines for this Pod, container and period.';render();}
  search.oninput=render;
  openLogs=async p=>{++logRequest;selectedPod=p;logNamespace=ns();source.value='current';setSavedPod(p);search.value='';mode();$('#logTitle').textContent='Logs · '+p;output.textContent='Loading containers…';archiveStatus.textContent='';if(!dialog.open)dialog.showModal();const id=logRequest;try{const detail=await api('/api/pod-detail?namespace='+encodeURIComponent(logNamespace)+'&pod='+encodeURIComponent(p));if(id!==logRequest)return;container.innerHTML=[...(detail.spec.initContainers||[]),...(detail.spec.containers||[])].map(x=>'<option value="'+esc(x.name)+'">'+esc(x.name)+'</option>').join('');loadLogs()}catch(e){if(id===logRequest)output.textContent=e.message}};
  loadLogs=async()=>{const id=++logRequest;archiveStatus.textContent='Loading logs…';allLogs='';render();try{
    if(source.value==='saved'){
      const requestedPod=savedPod.value;
      const result=await api('/api/history?'+new URLSearchParams({namespace:logNamespace||ns(),kind:'logs',days:days.value,pod:requestedPod,container:container.value,application:dialog.dataset.application||''}));
      if(id!==logRequest)return;savedRows=result.items;const chosen=container.value;
      const pods=result.pods||[...new Set(savedRows.map(x=>x.pod))];if(requestedPod&&!pods.includes(requestedPod))pods.push(requestedPod);
      savedPod.innerHTML='<option value="">All saved Pods</option>'+pods.sort().map(p=>'<option value="'+esc(p)+'">'+esc(p)+'</option>').join('');savedPod.value=requestedPod;
      container.innerHTML='<option value="">All saved containers</option>'+(result.containers||[...new Set(savedRows.map(x=>x.container))]).map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('');container.value=[...container.options].some(o=>o.value===chosen)?chosen:'';
      archiveStatus.textContent='Saved on PVC · '+result.retentionDays+' day retention'+(result.truncated?' · Results capped; narrow the Pod or period filter.':'')+(result.errors.length?' · Collection issues: '+result.errors.join('; '):'');renderSaved();
    }else{
      const q=new URLSearchParams({namespace:logNamespace||ns(),pod:selectedPod,container:container.value,previous:$('#previous').checked,since:since.value});
      const result=await api('/api/logs?'+q);if(id!==logRequest)return;allLogs=result.logs||'(no logs)';archiveStatus.textContent=result.archive?result.archive.message:'Archive status unavailable';render();
    }
  }catch(e){if(id===logRequest){allLogs=e.message;archiveStatus.textContent='Unable to load logs.';render()}}};
  source.onchange=()=>{mode();if(source.value==='current'){if(selectedPod)openLogs(selectedPod);else{allLogs='Select a live Pod from the Pods tab to load current logs.';archiveStatus.textContent='';render()}}else loadLogs()};
  container.onchange=loadLogs;since.onchange=loadLogs;days.onchange=()=>{container.value='';loadLogs()};savedPod.onchange=()=>{container.value='';loadLogs()};
  window.addEventListener('show-saved-logs',e=>{++logRequest;selectedPod=e.detail?.pod||'';dialog.dataset.application=e.detail?.application||'';logNamespace=ns();source.value='saved';setSavedPod(selectedPod);search.value='';container.innerHTML='<option value="">All saved containers</option>';mode();$('#logTitle').textContent=(dialog.dataset.application?'Application logs · '+dialog.dataset.application:'Saved logs')+' · '+logNamespace;if(!dialog.open)dialog.showModal();loadLogs()});
  dialog.addEventListener('close',()=>{if(!dialog.open){++logRequest;dialog.dataset.application=''}});
  $('#downloadLogs').onclick=()=>{const stamp=new Date().toISOString().replace(/[:.]/g,'-'),safeName=((source.value==='saved'?savedPod.value:selectedPod)||'namespace').replace(/[^a-zA-Z0-9._-]/g,'_'),blob=new Blob([output.textContent],{type:'text/plain;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=safeName+'-'+source.value+'-'+stamp+'.log';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
  $('#confirmRestart').addEventListener('click',()=>{setTimeout(loadNamespace,3000);setTimeout(loadNamespace,9000)});
  function metric(v,memory){const s=v.trim();if(s==='—'||s==='unavailable'||!s)return-1;const n=parseFloat(s),u=s.replace(/[0-9.]/g,'').toLowerCase();if(Number.isNaN(n))return-1;if(memory)return n*(u==='gi'?1024:u==='ki'?1/1024:1);return n*(u===''?1000:u==='m'?1:1000)}
  function valueFor(cell,type){const text=cell.textContent.trim();if(type==='cpu'||type==='memory')return metric(text,type==='memory');if(type==='age'){const time=Date.parse(cell.title||'');return Number.isNaN(time)?-1:time}if(type==='containers'){const m=text.match(/^(\d+)\s*\/\s*(\d+)$/);return m?Number(m[1])*1000+Number(m[2]):-1}if(type==='restarts'){const n=Number(text);return Number.isNaN(n)?-1:n}return text.toLowerCase()}
  function sortColumn(table,index,header,type){const highFirst=['cpu','memory','restarts','age'];const asc=header.dataset.order?header.dataset.order==='desc':!highFirst.includes(type);header.dataset.order=asc?'asc':'desc';header.textContent=header.textContent.replace(/\s*[↑↓]/g,'')+(asc?' ↑':' ↓');[...table.tBodies[0].rows].sort((a,b)=>{const av=valueFor(a.cells[index],type),bv=valueFor(b.cells[index],type);if(typeof av==='string')return asc?av.localeCompare(bv):bv.localeCompare(av);if(av<0&&bv<0)return 0;if(av<0)return 1;if(bv<0)return-1;return asc?av-bv:bv-av}).forEach(row=>table.tBodies[0].append(row))}
  function enhance(){try{const table=document.querySelector('#pods table');if(table&&overviewPods){const head=table.querySelector('thead tr');if(!head.querySelector('[data-containers]')){const th=document.createElement('th');th.dataset.containers='true';th.textContent='Containers';head.children[1].after(th)}table.querySelectorAll('tr[data-pod-row]').forEach(row=>{if(row.querySelector('[data-container-count]'))return;const pod=overviewPods.find(p=>p.metadata.name===row.dataset.podRow);if(!pod)return;const total=(pod.spec.containers||[]).length,ready=(pod.status.containerStatuses||[]).filter(c=>c.ready).length,cell=document.createElement('td');cell.dataset.containerCount='true';cell.textContent=`${ready}/${total}`;row.children[1].after(cell)});[...head.cells].forEach((h,i)=>{const label=h.textContent.replace(/[↑↓]/g,'').trim().toLowerCase(),types={name:'name',phase:'phase',containers:'containers',age:'age',cpu:'cpu',memory:'memory',restarts:'restarts'},type=types[label];if(type&&!h.dataset.sortable){h.dataset.sortable='true';h.style.cursor='pointer';h.title='Click to sort';h.onclick=()=>sortColumn(table,i,h,type)}})}const panel=[...document.querySelectorAll('#overview .dashpanel')].find(x=>x.querySelector('h2')?.textContent.startsWith('Workload readiness'));if(panel){panel.querySelector('h2').textContent='Workload readiness · needs attention first';const body=panel.querySelector('tbody');if(body)[...body.rows].sort((a,b)=>Number(b.cells[2].textContent!=='Healthy')-Number(a.cells[2].textContent!=='Healthy')).forEach(row=>body.append(row))}}catch(e){}}
  const podFilter={name:'',status:'all',restarts:'all'};
  function podLevel(pod){const phase=(pod.status||{}).phase||'Unknown',statuses=(pod.status||{}).containerStatuses||[],total=(pod.spec.containers||[]).length,ready=statuses.filter(c=>c.ready).length,waiting=statuses.some(c=>{const r=((c.state||{}).waiting||{}).reason||'';return ['CrashLoopBackOff','ImagePullBackOff','ErrImagePull','CreateContainerConfigError'].includes(r)});if(phase==='Failed'||phase==='Unknown'||waiting)return'critical';if(phase==='Pending')return'pending';if(phase==='Running'&&ready<total)return'degraded';if(phase==='Running')return'healthy';return'completed'}
  function applyPodFilter(table){if(!table||!overviewPods)return;let shown=0;table.querySelectorAll('tr[data-pod-row]').forEach(row=>{const pod=overviewPods.find(p=>p.metadata.name===row.dataset.podRow);if(!pod)return;const level=podLevel(pod),phase=(pod.status.phase||'').toLowerCase(),restarts=(pod.status.containerStatuses||[]).reduce((n,c)=>n+c.restartCount,0),name=pod.metadata.name.toLowerCase();row.classList.remove('pod-healthy','pod-pending','pod-degraded','pod-critical','pod-completed');row.classList.add('pod-'+level);const statusOk=podFilter.status==='all'||podFilter.status===phase||(podFilter.status==='running-ready'&&level==='healthy')||(podFilter.status==='notready'&&level==='degraded')||(podFilter.status==='problem'&&level==='critical');const restartOk=podFilter.restarts==='all'||(podFilter.restarts==='zero'&&restarts===0)||(podFilter.restarts==='oneplus'&&restarts>=1)||(podFilter.restarts==='fiveplus'&&restarts>=5);const visible=name.includes(podFilter.name)&&statusOk&&restartOk;row.hidden=!visible;if(visible)shown++});const count=document.querySelector('#podFilterCount');if(count)count.textContent=`${shown} matching pods`}
  function installPodFilters(table){const panel=document.querySelector('#pods');if(!panel||panel.querySelector('#podFilters'))return;const tools=document.createElement('div');tools.id='podFilters';tools.className='pod-filters';tools.innerHTML='<label>Pod name<input id="podNameFilter" placeholder="Search pod name…"></label><label>Status<select id="podStatusFilter"><option value="all">All statuses</option><option value="running">Running</option><option value="pending">Pending / starting</option><option value="notready">Running, not ready</option><option value="problem">Crash / failed</option></select></label><label>Restarts<select id="podRestartFilter"><option value="all">Any restart count</option><option value="zero">0 restarts</option><option value="oneplus">1+ restart</option><option value="fiveplus">5+ restarts</option></select></label><span id="podFilterCount"></span>';panel.querySelector('h2').after(tools);const name=tools.querySelector('#podNameFilter'),status=tools.querySelector('#podStatusFilter'),restarts=tools.querySelector('#podRestartFilter');name.value=podFilter.name;status.value=podFilter.status;restarts.value=podFilter.restarts;name.oninput=()=>{podFilter.name=name.value.trim().toLowerCase();applyPodFilter(table)};status.onchange=()=>{podFilter.status=status.value;applyPodFilter(table)};restarts.onchange=()=>{podFilter.restarts=restarts.value;applyPodFilter(table)};applyPodFilter(table)}
  function expandStatusFilter(){const status=document.querySelector('#podStatusFilter');if(!status||status.dataset.expanded)return;status.dataset.expanded='true';status.innerHTML='<option value="all">All pods</option><option value="running">Running (all)</option><option value="running-ready">Running and ready</option><option value="notready">Running, not ready</option><option value="pending">Pending</option><option value="succeeded">Succeeded</option><option value="failed">Failed</option><option value="unknown">Unknown</option><option value="problem">Crash / image error</option>';status.value=podFilter.status;status.onchange=()=>{podFilter.status=status.value;applyPodFilter(document.querySelector('#pods table'))}}
  const baseEnhance=enhance;enhance=()=>{baseEnhance();const table=document.querySelector('#pods table');if(table){installPodFilters(table);expandStatusFilter();applyPodFilter(table)}};
  setInterval(enhance,1000);document.head.insertAdjacentHTML('beforeend','<style>#pods [data-container-count]{color:#9ec7f1;font-size:12px;white-space:nowrap}#pods th[data-sortable]{color:#5ce0c6;user-select:none}.pod-filters{display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin:-2px 0 16px;padding:12px;background:#10213a;border:1px solid #2a4b6f;border-radius:9px}.pod-filters label{min-width:190px;color:#b9cde7;font-size:12px}.pod-filters input,.pod-filters select{margin-top:5px}.pod-filters span{color:#9ec7f1;font-size:12px;padding:9px 0}#pods tr.pod-healthy td,#pods tr.pod-pending td,#pods tr.pod-degraded td,#pods tr.pod-critical td,#pods tr.pod-completed td{background:transparent!important}#pods tr.pod-healthy td:first-child{box-shadow:inset 4px 0 #43dbc1}#pods tr.pod-pending td:first-child{box-shadow:inset 4px 0 #ffcd70}#pods tr.pod-degraded td:first-child{box-shadow:inset 4px 0 #ffb84d}#pods tr.pod-critical td:first-child{box-shadow:inset 4px 0 #ff7b91}#pods tr.pod-healthy td:nth-child(2),#pods tr.pod-healthy td:nth-child(3){color:#43dbc1;font-weight:650}#pods tr.pod-pending td:nth-child(2),#pods tr.pod-pending td:nth-child(3){color:#ffcd70;font-weight:650}#pods tr.pod-degraded td:nth-child(2),#pods tr.pod-degraded td:nth-child(3){color:#ffb84d;font-weight:650}#pods tr.pod-critical td:nth-child(2),#pods tr.pod-critical td:nth-child(3){color:#ff7b91;font-weight:650}</style>');
})();

/* Event filtering runs in the browser against the live Kubernetes Event list. */
(()=>{
  const state={text:'',type:'all',scope:'all'};
  const problem=/warning|fail|error|backoff|crash|unhealthy|unready|unschedul|evict|oom|pull|kill|deadline|forbidden|denied/i;
  function apply(table){
    let count=0;
    Array.prototype.forEach.call(table.tBodies[0].rows,function(row){
      const type=(row.cells[1]&&row.cells[1].textContent||'').trim();
      const reason=(row.cells[2]&&row.cells[2].textContent||'').trim();
      const message=(row.cells[3]&&row.cells[3].textContent||'').trim();
      const combined=(type+' '+reason+' '+message).toLowerCase();
      const typeMatch=state.type==='all'||type.toLowerCase()===state.type;
      const scopeMatch=state.scope==='all'||(state.scope==='problem'&&problem.test(type+' '+reason+' '+message))||(state.scope==='scheduling'&&/schedul|node|taint|affinity|insufficient/i.test(reason+' '+message));
      const textMatch=!state.text||combined.indexOf(state.text)>=0;
      row.hidden=!(typeMatch&&scopeMatch&&textMatch);
      if(!row.hidden)count++;
    });
    const label=document.querySelector('#eventFilterCount');if(label)label.textContent=count+' matching events';
  }
  function install(){
    const panel=document.querySelector('#events'),table=panel&&panel.querySelector('table');
    if(!table||panel.querySelector('#eventFilters')||!table.tBodies.length)return;
    const types=[];Array.prototype.forEach.call(table.tBodies[0].rows,function(row){const value=(row.cells[1]&&row.cells[1].textContent||'').trim().toLowerCase();if(value&&types.indexOf(value)<0)types.push(value)});
    const tools=document.createElement('div');tools.id='eventFilters';tools.className='event-filters';
    tools.innerHTML='<label>Search events<input id="eventTextFilter" placeholder="Reason, message, Pod, error…"></label><label>Event type<select id="eventTypeFilter"><option value="all">All event types</option>'+types.map(function(type){return '<option value="'+type+'">'+type.charAt(0).toUpperCase()+type.slice(1)+'</option>'}).join('')+'</select></label><label>Focus<select id="eventScopeFilter"><option value="all">All events</option><option value="problem">Problems / errors</option><option value="scheduling">Scheduling issues</option></select></label><span id="eventFilterCount"></span>';
    panel.querySelector('h2').after(tools);
    const text=tools.querySelector('#eventTextFilter'),type=tools.querySelector('#eventTypeFilter'),scope=tools.querySelector('#eventScopeFilter');
    text.oninput=function(){state.text=text.value.trim().toLowerCase();apply(table)};
    type.onchange=function(){state.type=type.value;apply(table)};
    scope.onchange=function(){state.scope=scope.value;apply(table)};
    apply(table);
  }
  setInterval(install,700);
  document.head.insertAdjacentHTML('beforeend','<style>.event-filters{display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin:-2px 0 16px;padding:12px;background:#10213a;border:1px solid #2a4b6f;border-radius:9px}.event-filters label{min-width:200px;color:#b9cde7;font-size:12px}.event-filters input,.event-filters select{margin-top:5px}.event-filters span{color:#9ec7f1;font-size:12px;padding:9px 0}</style>');
})();
