/* Optional Resource Explorer. Core dashboard startup does not depend on this file. */
(function(){
  function table(headers,rows,empty){return '<table><thead><tr>'+headers.map(function(h){return '<th>'+h+'</th>'}).join('')+'</tr></thead><tbody>'+(rows||'<tr><td colspan="'+headers.length+'">'+(empty||'No resources found.')+'</td></tr>')+'</tbody></table>'}
  function ports(service){return (service.spec.ports||[]).map(function(port){return (port.protocol||'TCP')+' '+port.port+' → '+(port.targetPort==null?port.port:port.targetPort)+(port.nodePort?' · nodePort '+port.nodePort:'')}).join('<br>')||'—'}
  async function loadResources(){
    var panel=$('#resources');
    panel.innerHTML='<h2>Resource Explorer <small>'+esc(ns())+'</small></h2><p class="muted">Loading live namespace resources…</p>';
    try{
      var d=await api('/api/resources?namespace='+encodeURIComponent(ns()));
      var hpas=(d.hpas||{}).items||[],services=(d.services||{}).items||[],ings=(d.ingresses||{}).items||[],slices=(d.endpointSlices||{}).items||[],pvcs=(d.pvcs||{}).items||[],quotas=(d.quotas||{}).items||[],limits=(d.limitRanges||{}).items||[],jobs=(d.jobs||{}).items||[],cronjobs=(d.cronjobs||{}).items||[];
      var cards='<div class="resource-cards"><div><b>'+hpas.length+'</b><span>Autoscalers</span></div><div><b>'+services.length+'</b><span>Services</span></div><div><b>'+ings.length+'</b><span>Ingresses</span></div><div><b>'+pvcs.length+'</b><span>PVCs</span></div><div><b>'+jobs.length+'</b><span>Jobs</span></div><div><b>'+cronjobs.length+'</b><span>CronJobs</span></div></div>';
      var hpaRows=hpas.map(function(h){var spec=h.spec||{},status=h.status||{},target=spec.scaleTargetRef||{},min=spec.minReplicas==null?1:spec.minReplicas,max=spec.maxReplicas==null?'—':spec.maxReplicas;return '<tr data-resource-kind="hpa" data-resource-name="'+esc(h.metadata.name)+'"><td><b>'+esc(h.metadata.name)+'</b></td><td>'+esc(target.kind||'—')+'/'+esc(target.name||'—')+'</td><td>'+esc(status.currentReplicas==null?'—':status.currentReplicas)+'</td><td>'+esc(min)+'–'+esc(max)+'</td><td><button class="hpa-edit" data-hpa="'+esc(h.metadata.name)+'" data-min="'+esc(min)+'" data-max="'+esc(max)+'">Edit range</button></td></tr>'}).join('');
      var serviceRows=services.map(function(s){var linked=slices.filter(function(slice){return ((slice.metadata.labels||{})['kubernetes.io/service-name'])===s.metadata.name}),total=linked.reduce(function(n,slice){return n+(slice.endpoints||[]).length},0),ready=linked.reduce(function(n,slice){return n+(slice.endpoints||[]).filter(function(ep){return (ep.conditions||{}).ready!==false}).length},0);return '<tr data-resource-kind="service" data-resource-name="'+esc(s.metadata.name)+'"><td><b>'+esc(s.metadata.name)+'</b></td><td>'+esc(s.spec.type||'ClusterIP')+'</td><td>'+ports(s)+'</td><td>'+ready+'/'+total+'</td></tr>'}).join('');
      var ingressRows=ings.map(function(i){var hosts=(i.spec.rules||[]).map(function(rule){return rule.host||'*'}).join(', ')||'—';return '<tr data-resource-kind="ingress" data-resource-name="'+esc(i.metadata.name)+'"><td><b>'+esc(i.metadata.name)+'</b></td><td>'+esc(hosts)+'</td></tr>'}).join('');
      var pvcRows=pvcs.map(function(p){return '<tr data-resource-kind="pvc" data-resource-name="'+esc(p.metadata.name)+'"><td><b>'+esc(p.metadata.name)+'</b></td><td>'+esc(p.status.phase||'Pending')+'</td><td>'+esc((p.status.capacity||{}).storage||'—')+'</td><td>'+esc(p.spec.storageClassName||'—')+'</td></tr>'}).join('');
      var jobRows=jobs.map(function(j){var status=j.status||{};return '<tr data-resource-kind="job" data-resource-name="'+esc(j.metadata.name)+'"><td><b>'+esc(j.metadata.name)+'</b></td><td>'+esc(status.succeeded||0)+'</td><td>'+esc(status.failed||0)+'</td><td>'+esc(status.active||0)+'</td></tr>'}).join('');
      var cronRows=cronjobs.map(function(c){var spec=c.spec||{},suspended=!!spec.suspend,schedule=spec.schedule||'—';return '<tr data-resource-kind="cronjob" data-resource-name="'+esc(c.metadata.name)+'"><td><b>'+esc(c.metadata.name)+'</b></td><td>'+esc(schedule)+'</td><td>'+(suspended?'Suspended':'Active')+'</td><td><button class="cronjob-edit" data-cron="'+esc(c.metadata.name)+'" data-schedule="'+esc(schedule)+'">Edit schedule</button> <button class="cronjob-action" data-cron="'+esc(c.metadata.name)+'" data-suspend="'+(suspended?'false':'true')+'">'+(suspended?'Resume':'Suspend')+'</button></td></tr>'}).join('');
      var quotaRows=quotas.map(function(q){var hard=(q.status||{}).hard||{};return '<tr data-resource-kind="resourcequota" data-resource-name="'+esc(q.metadata.name)+'"><td><b>'+esc(q.metadata.name)+'</b></td><td>'+esc(Object.keys(hard).map(function(key){return key+': '+hard[key]}).join(' · ')||'—')+'</td></tr>'}).join('');
      var limitRows=limits.map(function(l){return '<tr data-resource-kind="limitrange" data-resource-name="'+esc(l.metadata.name)+'"><td><b>'+esc(l.metadata.name)+'</b></td><td>'+esc((l.spec.limits||[]).map(function(item){return item.type}).join(', ')||'—')+'</td></tr>'}).join('');
      panel.innerHTML='<h2>Resource Explorer <small>'+esc(ns())+'</small></h2><p class="muted">Click a resource to view its Kubernetes describe output. Operational controls are shown only when enabled by Helm and permitted for your role.</p>'+cards+'<div class="resource-grid"><section><h3>Autoscalers</h3>'+table(['Name','Target','Current','Range','Action'],hpaRows,'No HPAs found.')+'</section><section><h3>Services & endpoints</h3>'+table(['Service','Type','Ports','Ready endpoints'],serviceRows,'No Services found.')+'</section><section><h3>Ingresses</h3>'+table(['Name','Hosts'],ingressRows,'No Ingresses found.')+'</section><section><h3>PersistentVolumeClaims</h3>'+table(['Name','Status','Capacity','StorageClass'],pvcRows,'No PVCs found.')+'</section><section><h3>Jobs</h3>'+table(['Name','Succeeded','Failed','Active'],jobRows,'No Jobs found.')+'</section><section><h3>CronJobs</h3>'+table(['Name','Schedule','Status','Action'],cronRows,'No CronJobs found.')+'</section><section><h3>Resource quotas</h3>'+table(['Name','Hard limits'],quotaRows,'No ResourceQuotas found.')+'</section><section><h3>Limit ranges</h3>'+table(['Name','Limit types'],limitRows,'No LimitRanges found.')+'</section></div>';
      panel.insertAdjacentHTML('beforeend','<section class="dashpanel"><h3>Discovered resources <small>read-only</small></h3><p class="muted">Browse namespaced API resources allowed by the dashboard ServiceAccount. Secret resources are intentionally excluded.</p><div class="tools"><label>Resource type<select id="discoveredKind"><option>Loading discovery…</option></select></label><button id="loadDiscovered">Load resources</button></div><div id="discoveredResults" class="discovery-list"></div></section>');
      api('/api/resource-discovery?namespace='+encodeURIComponent(ns())).then(function(discovery){$('#discoveredKind').innerHTML=discovery.resources.map(function(resource){return '<option value="'+esc(resource)+'">'+esc(resource)+'</option>'}).join('')||'<option>No accessible resources</option>'}).catch(function(error){$('#discoveredResults').innerHTML='<p class="error">'+esc(error.message)+'</p>'});
      $('#loadDiscovered').onclick=async function(){var resource=$('#discoveredKind').value,box=$('#discoveredResults');box.textContent='Loading '+resource+'…';try{var result=await api('/api/discovered-resources?namespace='+encodeURIComponent(ns())+'&resource='+encodeURIComponent(resource));var rows=(result.items||[]).map(function(item){var meta=item.metadata||{},conditions=(item.status||{}).conditions||[];return '<details class="insight"><summary><b>'+esc(item.kind||resource)+'/'+esc(meta.name)+'</b> · '+esc(conditions.map(function(c){return c.type+': '+c.status}).join(', ')||'No conditions')+'</summary><pre>'+esc(JSON.stringify({labels:meta.labels||{},spec:item.spec||{},status:item.status||{}},null,2))+'</pre></details>'}).join('');box.innerHTML=rows||'<p>No '+esc(resource)+' found in '+esc(ns())+'.</p>'}catch(error){box.innerHTML='<p class="error">'+esc(error.message)+'</p>'}};
      document.querySelectorAll('.cronjob-action').forEach(function(button){button.onclick=function(){openCronAction(button.dataset.cron,button.dataset.suspend==='true')}});
      document.querySelectorAll('.cronjob-edit').forEach(function(button){button.onclick=function(){openCronEdit(button.dataset.cron,button.dataset.schedule)}});
      document.querySelectorAll('.hpa-edit').forEach(function(button){button.onclick=function(){openHpaEdit(button.dataset.hpa,button.dataset.min,button.dataset.max)}});
      document.querySelectorAll('#resources tr[data-resource-kind]').forEach(function(row){row.title='Click to view Kubernetes describe output';row.style.cursor='pointer';row.onclick=function(event){if(event.target.closest('button'))return;showResourceDescribe(row.dataset.resourceKind,row.dataset.resourceName)}});
    }catch(e){panel.innerHTML='<h2>Resource Explorer</h2><p class="error">'+esc(e.message)+'</p>'}
  }
  var cronTarget;
  function openCronAction(name,suspend){cronTarget={name:name,suspend:suspend};$('#cronTitle').textContent=(suspend?'Suspend':'Resume')+' CronJob';$('#cronText').textContent='You are about to '+(suspend?'suspend':'resume')+' cronjob/'+name+' in namespace '+ns()+'.';$('#cronConfirmation').value='';$('#cronConfirmation').placeholder=suspend?'SUSPEND':'RESUME';$('#confirmCron').textContent=suspend?'Suspend CronJob':'Resume CronJob';$('#cronDialog').showModal()}
  $('#confirmCron').onclick=async function(event){event.preventDefault();try{var response=await api('/api/cronjob-suspend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({namespace:ns(),kind:'cronjob',name:cronTarget.name,suspend:cronTarget.suspend,confirmation:$('#cronConfirmation').value})});$('#cronDialog').close();note(response.message);loadResources()}catch(e){note(e.message,true)}};
  function openCronEdit(name,schedule){$('#cronEditText').textContent='Update the schedule for cronjob/'+name+' in namespace '+ns()+'.';$('#cronSchedule').value=schedule;$('#cronEditConfirmation').value='';$('#confirmCronEdit').dataset.cron=name;$('#cronEditDialog').showModal()}
  $('#confirmCronEdit').onclick=async function(event){event.preventDefault();try{var response=await api('/api/cronjob-edit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({namespace:ns(),kind:'cronjob',name:event.currentTarget.dataset.cron,schedule:$('#cronSchedule').value,confirmation:$('#cronEditConfirmation').value})});$('#cronEditDialog').close();note(response.message);loadResources()}catch(e){note(e.message,true)}};
  function openHpaEdit(name,min,max){$('#hpaEditText').textContent='Update the replica range for hpa/'+name+' in namespace '+ns()+'.';$('#hpaMin').value=min;$('#hpaMax').value=max;$('#hpaEditConfirmation').value='';$('#confirmHpaEdit').dataset.hpa=name;$('#hpaEditDialog').showModal()}
  $('#confirmHpaEdit').onclick=async function(event){event.preventDefault();try{var response=await api('/api/hpa-edit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({namespace:ns(),kind:'hpa',name:event.currentTarget.dataset.hpa,minReplicas:$('#hpaMin').value,maxReplicas:$('#hpaMax').value,confirmation:$('#hpaEditConfirmation').value})});$('#hpaEditDialog').close();note(response.message);loadResources()}catch(e){note(e.message,true)}};
  async function showResourceDescribe(kind,name){var box=$('#podDetail');box.innerHTML='<h2>Describe '+esc(kind)+' · '+esc(name)+'</h2><p class="muted">Loading Kubernetes describe output…</p>';$('#podDialog').showModal();try{var response=await api('/api/resource-describe?namespace='+encodeURIComponent(ns())+'&kind='+encodeURIComponent(kind)+'&name='+encodeURIComponent(name));box.innerHTML='<h2>Describe '+esc(kind)+' · '+esc(name)+'</h2><pre class="describe-output">'+esc(response.output||'No output returned.')+'</pre>'}catch(e){box.innerHTML='<h2>Describe '+esc(kind)+' · '+esc(name)+'</h2><p class="error">'+esc(e.message)+'</p>'}}
  document.querySelector('[data-tab="resources"]').onclick=function(){document.querySelectorAll('.tabs button').forEach(function(button){button.classList.toggle('active',button.dataset.tab==='resources')});document.querySelectorAll('.panel').forEach(function(panel){panel.classList.toggle('hidden',panel.id!=='resources')});loadResources()};
  document.head.insertAdjacentHTML('beforeend','<style>.resource-cards{display:grid;grid-template-columns:repeat(6,minmax(105px,1fr));gap:12px;margin:14px 0}.resource-cards div{background:#142542;border:1px solid #2c4d74;border-radius:9px;padding:14px}.resource-cards b{display:block;font-size:24px;color:#5ce0c6}.resource-cards span{color:#a9c7ed;font-size:12px}.resource-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.resource-grid section{background:#142542;border:1px solid #2c4d74;border-radius:9px;padding:14px;overflow:auto}.resource-grid h3{margin:0 0 12px}@media(max-width:1100px){.resource-cards{grid-template-columns:repeat(3,1fr)}.resource-grid{grid-template-columns:1fr}}</style>');
})();
