apiVersion: v1
kind: Service
metadata: { name: {{ include "kubernetes-operations-dashboard.fullname" . }} }
spec:
  type: {{ .Values.service.type }}
  selector: { app.kubernetes.io/name: {{ include "kubernetes-operations-dashboard.name" . }} }
  ports: [{ name: http, port: {{ .Values.service.port }}, targetPort: http }]
